### ISSUE TITLE
SQL to create tl_layout table fails on MariaDB 10.2.16

### ISSUE THREAD

**Issue by DanMan** [contao/manager-bundle#77] opened 2018-07-09 12:41 UTC
The problem is the column `rows`. It didn't like that it was used unquoted (it's a [reserved word](https://mariadb.com/kb/en/library/reserved-words/) after all). I issued the SQL manually with the column name quoted with backticks, and then it worked.

Possibly also a problem on MySQL.

**Comment by fritzmg** [comment] 2018-07-09 12:45
You need at least PHP 7.1 and then update all your dependencies.

**Comment by xchs** [comment] 2018-07-09 12:49
Duplicate of https://github.com/contao/core-bundle/issues/918, https://github.com/contao/installation-bundle/pull/70

**Comment by DanMan** [comment] 2018-07-09 13:05
@fritzmg I'm running PHP 7.2.7 (Fedora), and I don't see what PHP has to do with that. It pulled in doctrine/dbal v2.5.13 anyway.

I wanted to use Contao LTS which means 4.4, and now it seems like I can't.

**Comment by xchs** [comment] 2018-07-09 13:14
What's you `doctrine/dbal` version?

See https://github.com/contao/installation-bundle/issues/92

**Comment by DanMan** [comment] 2018-07-09 13:15
I just did a composer update and it's now at v2.7.1. Does that fix it?

As per your link it should. Thanks for the help.

**Comment by xchs** [comment] 2018-07-09 13:16
I think so, yes.

**Comment by fritzmg** [comment] 2018-07-09 13:18
> @fritzmg I'm running PHP 7.2.7 (Fedora), and I don't see what PHP has to do with that. It pulled in doctrine/dbal v2.5.13 anyway.

You need at least `doctrine/dbal` in version `2.7` (iirc) to fix the problems with the `rows` keyword. And in order to have `doctrine/dbal` in that version, you need at least PHP 7.1. That's why I am asking for the PHP version and why I am suggesting that you should verify that you have the latest package updates ;)

**Closed as completed** 2018-07-09 13:21 UTC

**Comment by DanMan** [comment] 2018-07-09 13:22
Someone should probably add to the docs that you need to update your deps. before you run the install.

**Comment by fritzmg** [comment] 2018-07-09 13:27
It currently happens only with Contao 4.4 when using the release archive or `composer create-project`. This problem will not happen anymore in future versions of Contao because there will be no release archive anymore and the `composer.lock` of the managed edition will be removed.

**Comment by xchs** [comment] 2018-07-09 13:27
If the `composer.lock` file gets removed (as suggested in https://github.com/contao/installation-bundle/issues/92) then a `composer install` or `composer create-project` command will always run `composer update`, anyway.

**Comment by DanMan** [comment] 2018-07-09 13:28
Even better. Cheers.
